package com.remodex.mobile.data

import com.remodex.mobile.core.model.CODEX_PAIRING_QR_VERSION
import com.remodex.mobile.core.model.CODEX_SECURE_CLOCK_SKEW_TOLERANCE_SECONDS
import com.remodex.mobile.core.model.CodexPairingQRPayload
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject

private val pairingJson =
    Json {
        ignoreUnknownKeys = true
        coerceInputValues = true
    }

private const val QR_SCANNER_BRIDGE_UPDATE_COMMAND = "npm install -g remodex@latest"

sealed class QrPairingValidationResult {
    data class Success(
        val payload: CodexPairingQRPayload,
    ) : QrPairingValidationResult()

    data class ScanError(
        val message: String,
    ) : QrPairingValidationResult()

    data class BridgeUpdateRequired(
        val title: String,
        val message: String,
        val command: String = QR_SCANNER_BRIDGE_UPDATE_COMMAND,
    ) : QrPairingValidationResult()
}

/**
 * Classifies scanned QR payloads (parity with [QRScannerPairingValidator.swift](CodexMobile/CodexMobile/Views/QRScannerPairingValidator.swift)).
 */
fun validatePairingQrCode(
    code: String,
    nowEpochMillis: Long = System.currentTimeMillis(),
): QrPairingValidationResult {
    val trimmed = code.trim()
    val payload =
        runCatching {
            pairingJson.decodeFromString<CodexPairingQRPayload>(trimmed)
        }.getOrNull()

    if (payload != null) {
        if (payload.v != CODEX_PAIRING_QR_VERSION) {
            return QrPairingValidationResult.BridgeUpdateRequired(
                title = "Update Remodex on your Mac before scanning",
                message =
                    "This QR code was generated by a different Remodex npm version. " +
                        "Update the package on your Mac to the latest release before scanning a new QR code.",
            )
        }
        if (payload.relay.trim().isEmpty()) {
            return QrPairingValidationResult.ScanError(
                "QR code is missing the relay URL. Re-generate the code from the bridge.",
            )
        }
        if (payload.sessionId.trim().isEmpty()) {
            return QrPairingValidationResult.ScanError(
                "QR code is missing the session ID. Re-generate the code from the bridge.",
            )
        }
        val skewMillis = (CODEX_SECURE_CLOCK_SKEW_TOLERANCE_SECONDS * 1000).toLong()
        if (nowEpochMillis > payload.expiresAt + skewMillis) {
            return QrPairingValidationResult.ScanError(
                "This pairing QR code has expired. Generate a new one from the Mac bridge.",
            )
        }
        return QrPairingValidationResult.Success(payload)
    }

    if (looksLikeRemodexPairingPayload(trimmed)) {
        return QrPairingValidationResult.BridgeUpdateRequired(
            title = "Update Remodex on your Mac before scanning",
            message =
                "This QR code looks like it came from an older Remodex bridge. " +
                    "Update the npm package on your Mac to the latest release before scanning a new QR code.",
        )
    }

    return QrPairingValidationResult.ScanError(
        "Not a valid secure pairing code. Make sure you're scanning a QR from the latest Remodex bridge.",
    )
}

private fun looksLikeRemodexPairingPayload(raw: String): Boolean {
    val obj =
        runCatching {
            pairingJson.parseToJsonElement(raw).jsonObject
        }.getOrNull() ?: return false
    val pairingKeys =
        setOf(
            "relay",
            "sessionId",
            "macDeviceId",
            "macIdentityPublicKey",
            "expiresAt",
            "v",
        )
    return obj.keys.any { it in pairingKeys }
}
